// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from connexor.proto

package fi.seco.lexical.connexor.model;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class LANGResponse implements Externalizable, Message<LANGResponse> {

	public static Schema<LANGResponse> getSchema() {
		return SCHEMA;
	}

	public static LANGResponse getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	static final LANGResponse DEFAULT_INSTANCE = new LANGResponse();

	// non-private fields
	// see http://developer.android.com/guide/practices/design/performance.html#package_inner
	String lang;
	String error;

	public LANGResponse() {

	}

	// getters and setters

	// lang

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	// error

	public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}

	// java serialization

	@Override
	public void readExternal(ObjectInput in) throws IOException {
		GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
	}

	// message method

	@Override
	public Schema<LANGResponse> cachedSchema() {
		return SCHEMA;
	}

	static final Schema<LANGResponse> SCHEMA = new Schema<LANGResponse>() {
		// schema methods

		@Override
		public LANGResponse newMessage() {
			return new LANGResponse();
		}

		@Override
		public Class<LANGResponse> typeClass() {
			return LANGResponse.class;
		}

		@Override
		public String messageName() {
			return LANGResponse.class.getSimpleName();
		}

		@Override
		public String messageFullName() {
			return LANGResponse.class.getName();
		}

		@Override
		public boolean isInitialized(LANGResponse message) {
			return true;
		}

		@Override
		public void mergeFrom(Input input, LANGResponse message) throws IOException {
			for (int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
				switch (number) {
				case 0:
					return;
				case 2:
					message.lang = input.readString();
					break;
				case 255:
					message.error = input.readString();
					break;
				default:
					input.handleUnknownField(number, this);
				}
		}

		@Override
		public void writeTo(Output output, LANGResponse message) throws IOException {
			if (message.lang != null) output.writeString(2, message.lang, false);

			if (message.error != null) output.writeString(255, message.error, false);
		}

		@Override
		public String getFieldName(int number) {
			switch (number) {
			case 2:
				return "lang";
			case 255:
				return "error";
			default:
				return null;
			}
		}

		@Override
		public int getFieldNumber(String name) {
			final Integer number = fieldMap.get(name);
			return number == null ? 0 : number.intValue();
		}

		final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();
		{
			fieldMap.put("lang", 2);
			fieldMap.put("error", 255);
		}
	};

}
