// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from connexor.proto

package fi.seco.lexical.connexor.model;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MTResponse implements Externalizable, Message<MTResponse> {
	public static final class Token implements Externalizable, Message<Token> {
		public static final class Reading implements Externalizable, Message<Reading> {

			public static Schema<Reading> getSchema() {
				return SCHEMA;
			}

			public static Reading getDefaultInstance() {
				return DEFAULT_INSTANCE;
			}

			static final Reading DEFAULT_INSTANCE = new Reading();

			// non-private fields
			// see http://developer.android.com/guide/practices/design/performance.html#package_inner
			String baseform;
			String morpho;
			String custom;

			public Reading() {

			}

			// getters and setters

			// baseform

			public String getBaseform() {
				return baseform;
			}

			public void setBaseform(String baseform) {
				this.baseform = baseform;
			}

			// morpho

			public String getMorpho() {
				return morpho;
			}

			public void setMorpho(String morpho) {
				this.morpho = morpho;
			}

			// custom

			public String getCustom() {
				return custom;
			}

			public void setCustom(String custom) {
				this.custom = custom;
			}

			// java serialization

			@Override
			public void readExternal(ObjectInput in) throws IOException {
				GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
			}

			@Override
			public void writeExternal(ObjectOutput out) throws IOException {
				GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
			}

			// message method

			@Override
			public Schema<Reading> cachedSchema() {
				return SCHEMA;
			}

			static final Schema<Reading> SCHEMA = new Schema<Reading>() {
				// schema methods

				@Override
				public Reading newMessage() {
					return new Reading();
				}

				@Override
				public Class<Reading> typeClass() {
					return Reading.class;
				}

				@Override
				public String messageName() {
					return Reading.class.getSimpleName();
				}

				@Override
				public String messageFullName() {
					return Reading.class.getName();
				}

				@Override
				public boolean isInitialized(Reading message) {
					return true;
				}

				@Override
				public void mergeFrom(Input input, Reading message) throws IOException {
					for (int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
						switch (number) {
						case 0:
							return;
						case 1:
							message.baseform = input.readString();
							break;
						case 2:
							message.morpho = input.readString();
							break;
						case 3:
							message.custom = input.readString();
							break;
						default:
							input.handleUnknownField(number, this);
						}
				}

				@Override
				public void writeTo(Output output, Reading message) throws IOException {
					if (message.baseform != null) output.writeString(1, message.baseform, false);

					if (message.morpho != null) output.writeString(2, message.morpho, false);

					if (message.custom != null) output.writeString(3, message.custom, false);
				}

				@Override
				public String getFieldName(int number) {
					switch (number) {
					case 1:
						return "baseform";
					case 2:
						return "morpho";
					case 3:
						return "custom";
					default:
						return null;
					}
				}

				@Override
				public int getFieldNumber(String name) {
					final Integer number = fieldMap.get(name);
					return number == null ? 0 : number.intValue();
				}

				final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();
				{
					fieldMap.put("baseform", 1);
					fieldMap.put("morpho", 2);
					fieldMap.put("custom", 3);
				}
			};

		}

		public static Schema<Token> getSchema() {
			return SCHEMA;
		}

		public static Token getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		static final Token DEFAULT_INSTANCE = new Token();

		// non-private fields
		// see http://developer.android.com/guide/practices/design/performance.html#package_inner
		String textform;
		Integer position;
		Integer length;
		List<Reading> reading;

		public Token() {

		}

		// getters and setters

		// textform

		public String getTextform() {
			return textform;
		}

		public void setTextform(String textform) {
			this.textform = textform;
		}

		// position

		public Integer getPosition() {
			return position;
		}

		public void setPosition(Integer position) {
			this.position = position;
		}

		// length

		public Integer getLength() {
			return length;
		}

		public void setLength(Integer length) {
			this.length = length;
		}

		// reading

		public List<Reading> getReadingList() {
			return reading;
		}

		public void setReadingList(List<Reading> reading) {
			this.reading = reading;
		}

		// java serialization

		@Override
		public void readExternal(ObjectInput in) throws IOException {
			GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
		}

		@Override
		public void writeExternal(ObjectOutput out) throws IOException {
			GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
		}

		// message method

		@Override
		public Schema<Token> cachedSchema() {
			return SCHEMA;
		}

		static final Schema<Token> SCHEMA = new Schema<Token>() {
			// schema methods

			@Override
			public Token newMessage() {
				return new Token();
			}

			@Override
			public Class<Token> typeClass() {
				return Token.class;
			}

			@Override
			public String messageName() {
				return Token.class.getSimpleName();
			}

			@Override
			public String messageFullName() {
				return Token.class.getName();
			}

			@Override
			public boolean isInitialized(Token message) {
				return true;
			}

			@Override
			public void mergeFrom(Input input, Token message) throws IOException {
				for (int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
					switch (number) {
					case 0:
						return;
					case 1:
						message.textform = input.readString();
						break;
					case 2:
						message.position = input.readInt32();
						break;
					case 3:
						message.length = input.readInt32();
						break;
					case 4:
						if (message.reading == null) message.reading = new ArrayList<Reading>();
						message.reading.add(input.mergeObject(null, Reading.getSchema()));
						break;

					default:
						input.handleUnknownField(number, this);
					}
			}

			@Override
			public void writeTo(Output output, Token message) throws IOException {
				if (message.textform != null) output.writeString(1, message.textform, false);

				if (message.position != null) output.writeInt32(2, message.position, false);

				if (message.length != null) output.writeInt32(3, message.length, false);

				if (message.reading != null) for (Reading reading : message.reading)
					if (reading != null) output.writeObject(4, reading, Reading.getSchema(), true);

			}

			@Override
			public String getFieldName(int number) {
				switch (number) {
				case 1:
					return "textform";
				case 2:
					return "position";
				case 3:
					return "length";
				case 4:
					return "reading";
				default:
					return null;
				}
			}

			@Override
			public int getFieldNumber(String name) {
				final Integer number = fieldMap.get(name);
				return number == null ? 0 : number.intValue();
			}

			final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();
			{
				fieldMap.put("textform", 1);
				fieldMap.put("position", 2);
				fieldMap.put("length", 3);
				fieldMap.put("reading", 4);
			}
		};

	}

	public static Schema<MTResponse> getSchema() {
		return SCHEMA;
	}

	public static MTResponse getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	static final MTResponse DEFAULT_INSTANCE = new MTResponse();

	// non-private fields
	// see http://developer.android.com/guide/practices/design/performance.html#package_inner
	List<Token> token;
	String error;

	public MTResponse() {

	}

	// getters and setters

	// token

	public List<Token> getTokenList() {
		return token;
	}

	public void setTokenList(List<Token> token) {
		this.token = token;
	}

	// error

	public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}

	// java serialization

	@Override
	public void readExternal(ObjectInput in) throws IOException {
		GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
	}

	// message method

	@Override
	public Schema<MTResponse> cachedSchema() {
		return SCHEMA;
	}

	static final Schema<MTResponse> SCHEMA = new Schema<MTResponse>() {
		// schema methods

		@Override
		public MTResponse newMessage() {
			return new MTResponse();
		}

		@Override
		public Class<MTResponse> typeClass() {
			return MTResponse.class;
		}

		@Override
		public String messageName() {
			return MTResponse.class.getSimpleName();
		}

		@Override
		public String messageFullName() {
			return MTResponse.class.getName();
		}

		@Override
		public boolean isInitialized(MTResponse message) {
			return true;
		}

		@Override
		public void mergeFrom(Input input, MTResponse message) throws IOException {
			for (int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
				switch (number) {
				case 0:
					return;
				case 2:
					if (message.token == null) message.token = new ArrayList<Token>();
					message.token.add(input.mergeObject(null, Token.getSchema()));
					break;

				case 255:
					message.error = input.readString();
					break;
				default:
					input.handleUnknownField(number, this);
				}
		}

		@Override
		public void writeTo(Output output, MTResponse message) throws IOException {
			if (message.token != null) for (Token token : message.token)
				if (token != null) output.writeObject(2, token, Token.getSchema(), true);

			if (message.error != null) output.writeString(255, message.error, false);
		}

		@Override
		public String getFieldName(int number) {
			switch (number) {
			case 2:
				return "token";
			case 255:
				return "error";
			default:
				return null;
			}
		}

		@Override
		public int getFieldNumber(String name) {
			final Integer number = fieldMap.get(name);
			return number == null ? 0 : number.intValue();
		}

		final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();
		{
			fieldMap.put("token", 2);
			fieldMap.put("error", 255);
		}
	};

}
