// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from connexor.proto

package fi.seco.lexical.connexor.model;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class MSUMResponse implements Externalizable, Message<MSUMResponse> {

	public static Schema<MSUMResponse> getSchema() {
		return SCHEMA;
	}

	public static MSUMResponse getDefaultInstance() {
		return DEFAULT_INSTANCE;
	}

	static final MSUMResponse DEFAULT_INSTANCE = new MSUMResponse();

	// non-private fields
	// see http://developer.android.com/guide/practices/design/performance.html#package_inner
	String summary;
	String error;

	public MSUMResponse() {

	}

	// getters and setters

	// summary

	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	// error

	public String getError() {
		return error;
	}

	public void setError(String error) {
		this.error = error;
	}

	// java serialization

	@Override
	public void readExternal(ObjectInput in) throws IOException {
		GraphIOUtil.mergeDelimitedFrom(in, this, SCHEMA);
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, SCHEMA);
	}

	// message method

	@Override
	public Schema<MSUMResponse> cachedSchema() {
		return SCHEMA;
	}

	static final Schema<MSUMResponse> SCHEMA = new Schema<MSUMResponse>() {
		// schema methods

		@Override
		public MSUMResponse newMessage() {
			return new MSUMResponse();
		}

		@Override
		public Class<MSUMResponse> typeClass() {
			return MSUMResponse.class;
		}

		@Override
		public String messageName() {
			return MSUMResponse.class.getSimpleName();
		}

		@Override
		public String messageFullName() {
			return MSUMResponse.class.getName();
		}

		@Override
		public boolean isInitialized(MSUMResponse message) {
			return true;
		}

		@Override
		public void mergeFrom(Input input, MSUMResponse message) throws IOException {
			for (int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
				switch (number) {
				case 0:
					return;
				case 2:
					message.summary = input.readString();
					break;
				case 255:
					message.error = input.readString();
					break;
				default:
					input.handleUnknownField(number, this);
				}
		}

		@Override
		public void writeTo(Output output, MSUMResponse message) throws IOException {
			if (message.summary != null) output.writeString(2, message.summary, false);

			if (message.error != null) output.writeString(255, message.error, false);
		}

		@Override
		public String getFieldName(int number) {
			switch (number) {
			case 2:
				return "summary";
			case 255:
				return "error";
			default:
				return null;
			}
		}

		@Override
		public int getFieldNumber(String name) {
			final Integer number = fieldMap.get(name);
			return number == null ? 0 : number.intValue();
		}

		final java.util.HashMap<String, Integer> fieldMap = new java.util.HashMap<String, Integer>();
		{
			fieldMap.put("summary", 2);
			fieldMap.put("error", 255);
		}
	};

}
